
ARG BALENA_ARCH=%%BALENA_ARCH%%

# https://github.com/klutchell/balena-tailscale
FROM bh.cr/gh_klutchell/tailscale-amd64/6401e03bfc2272906efded59f6b19257:1.98.8 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/e9d193a80a591bc318661efc0aa5689b:1.98.8 AS balena-tailscale-aarch64

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}

ENV TS_HOSTNAME="homeassistant"
ENV TS_EXTRA_ARGS="--reset"
