FROM koenkk/zigbee2mqtt:1.36.0@sha256:4de1ee53d67a9b4556045c34a2722bfd2348dabbefcb792e862643104d3e9fd0

# install default configuration for first boot
# future changes must be made via the UI
COPY configuration.yaml /app/
