FROM koenkk/zigbee2mqtt:1.33.2@sha256:44a431c18fffea0a56cf5fcd1c3c5ad554d1b207bd0525e75ee154928c58cb05

# install default configuration for first boot
# future changes must be made via the UI
COPY configuration.yaml /app/
